name: sofia_redux
channels:
  - conda-forge
  - defaults
dependencies:
  - astropy>=6.0.0
  - astroquery>=0.4.6
  - bottleneck>=1.3.7
  - cloudpickle>=3.0.0
  - configobj>=5.0.8
  - cycler>=0.12.1
  - dill>=0.3.7
  - graphviz>=2.40
  - imageio>=2.33.1
  - joblib>=1.3.2
  - matplotlib>=3.8.2
  - more-itertools>=10.2.0
  - numba>=0.58.1
  - numpy>=1.26.3
  - pandas>=2.2.0
  - photutils>=1.10.0
  - pip>=20.3
  - psutil>=5.9.8
  - pyqt>=5.9.2
  - pytest>=7.4.4
  - pytest-astropy>=0.11.0
  - pytest-astropy-header>=0.2.2
  - pytest-cov>=4.1.0
  - pytest-mock>=3.12.0
  - pytest-qt>4.3.1
  - pytest-remotedata>=0.4.1
  - pytest-timeout>=2.2.0
  - python>=3.11
  - regex>=2023.12.25
  - scikit-learn>=1.4.0
  - scipy>=1.12.0
  - sphinx-astropy>=1.9.1
