name: Build Documentation

on:
  push:
    branches:
      - sdc-dev
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-docs:
    runs-on: self-hosted
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install '.[docs]' PyQt5
      - name: Sphinx build
        run: |
          sphinx-build docs docs/_build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/_build/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3